name: L1

# plugins:
#   - name: solidity
#   - name: infura
#   - name: etherscan

# default_ecosystem: ethereum

# ethereum:
#   default_network: sepolia
#   sepolia:
#     default_provider: infura

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.1.0 # Specify the version or use latest
